#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

k=0;

for arg in "$@"
do
    k=$(( k + 1 ));
done

if [ $k -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
else
    scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
fi
