#!/usr/bin/env bash
# Bash script to set up nginx web server

# Installing nginx
sudo apt-get update
sudo apt-get install nginx -y

# Adjusting the Firewall
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

# Setting permission for the /var/www directory
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Editing the index.html file
echo "Hello World!" > /var/www/html/index.html

# Restarting ngnix server to load up changes
sudo service nginx restart
