#!/usr/bin/env bash
# Bash script to set up nginx web server

# Installing nginx
sudo apt-get update
sudo apt-get install nginx -y

# Adjusting the Firewall
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

# Editing the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restarting ngnix server to load up changes
sudo service nginx restart
