#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Installing nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Editing the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirecting a specific page
new_string="\tserver_name _;\n \trewrite ^/redirect_me/$ http://x.com permanent;\n \trewrite ^/redirect_me/$ http://x.com permanent; "
sudo sed -i "s|^[^#].*server_name.*;|$new_string|" /etc/nginx/sites-enabled/default;

# Custom 404 page
sudo sed -i "s|^[^#].*location / {*;|$new_string|" /etc/nginx/sites-enabled/default;
location / {

# Removing temporary files being saved in the same directory
# This causes the nginx server to fail, because their are
# two default servers in two different files
sudo rm -rf /etc/nginx/sites-enabled/default~

# Restarting ngnix server to load up changes
sudo service nginx restart
