#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Installing nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Editing the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirecting a specific page
new_string="\tserver_name _;\n \trewrite ^/redirect_me/$ http://x.com permanent;\n \trewrite ^/redirect_me/$ http://x.com permanent; "
sudo sed -i "s|^[^#].*server_name.*;|$new_string|" /etc/nginx/sites-enabled/default;

# Creating the 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Directing 404 error to custom page
rep_str="\terror_page 404 /custom_404.html;\n \tlocation = /custom_404.html {\n \t\troot /usr/share/nginx/html;\n \t\tinternal;"
sudo sed -i "s|^[^#].*location \/ {$|$rep_str|" /etc/nginx/sites-enabled/default;

# Removing temporary files being saved in the same directory
# This causes the nginx server to fail, because their are
# two default servers in two different files
sudo rm -rf /etc/nginx/sites-enabled/default~

# Restarting ngnix server to load up changes
sudo service nginx restart
