#!/usr/bin/env bash
# Install & configure HAproxy on lb-01 server to send traffic to web-01 & web-02

# Installing HAProxy
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

# Enabling HAProxy Script
echo "ENABLE=1" | sudo tee -a /etc/default/haproxy

# Edit config file
__config="
frontend lb-frontend
	 bind *:80
	 mode http
	 default_backend lb-backend

backend lb-backend
	balance roundrobin
	server 118886-web-01 54.237.64.177:80 check
	server 118886-web-02 52.91.136.101:80 check

"
echo "$__config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
