#!/usr/bin/env bash
# Fixed Failed to connect to 0 port 80: Connection refused
sudo apt install nginx -y
sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
