#!/usr/bin/env bash
# Bash script that displays I am invinciblels! when receiving a SIGTERM signal
a=0

while [ "$a" -le "100" ]
do
    trap 'echo "I am invincible!!!"' SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
exit 0
