#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 with branches
# at 4, 9, 17
LIMIT=20
a=1
while [ $a -le $LIMIT ]
do
    echo $a
    case $a in
    4 )
	echo "bad luck from China";;
    9 )
	echo "bad luck from Japan";;
    17 )
	echo "bad luck from Italy";;
    esac

    (( a1`++ ))
done
exit 0
