#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

LIMIT=101
i=1

while [ $i -lt $LIMIT ]
do
    (( a = i % 3 ))
    (( b = i % 5 ))
    if [ $a -eq 0 ] && [ $b -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $a -eq 0 ]
    then
	echo "Fizz"
    elif [ $b -eq 0 ]
    then
	echo "Buzz"
    else
	echo $i
    fi

    (( i++ ))
done
