#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the
# 9th iteration, displays Best School and then Hi on a new line.

LIMIT=1
while [ "$LIMIT" -le "10" ]
do
    echo "Best School"
    if [ "$LIMIT" -eq "9" ]
    then
        echo "Hi"
    fi

    (( LIMIT++ ))
done
exit 0
