#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts ~/temp_hosts

p1=$(grep "localhost" ~/temp_hosts)
if [ "$p1" ]
then
    sed -i '/\tlocalhost/c\127.0.0.2\tlocalhost' ~/temp_hosts
else
    echo -e "127.0.0.2\tlocalhost" >> ~/temp_hosts
fi

p2=$(grep "facebook" ~/temp_hosts)
if [ "$p2" ]
then
    sed -i '/\tfacebook/c\8.8.8.8\tfacebook' ~/temp_hosts
else
    echo -e "8.8.8.8\tfacebook" >> ~/temp_hosts
fi

cp ~/temp_hosts /etc/hosts
